<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Business Insights Report</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Portfolio</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
<li>
  <a href="projects.html">Projects</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Business Insights Report</h1>

</div>


<hr />
<div id="section" class="section level2">
<h2></h2>
<div id="section-1" class="section level3">
<h3></h3>
<pre class="r"><code>str(business_data)</code></pre>
<pre><code>## &#39;data.frame&#39;:    48 obs. of  7 variables:
##  $ quarter        : chr  &quot;Q1&quot; &quot;Q2&quot; &quot;Q3&quot; &quot;Q4&quot; ...
##  $ channel        : chr  &quot;Online&quot; &quot;Online&quot; &quot;Online&quot; &quot;Online&quot; ...
##  $ year           : int  2023 2023 2023 2023 2023 2023 2023 2023 2023 2023 ...
##  $ revenue        : int  314019 288825 296739 287699 351721 324090 348699 328609 368558 362724 ...
##  $ customers      : int  1200 1340 1405 1241 1441 1647 1650 1556 1524 1690 ...
##  $ conversion_rate: num  3.9 3.4 2.9 3.6 NA 3.8 3.4 3.7 4.3 3.6 ...
##  $ region         : chr  &quot;North&quot; &quot;South&quot; &quot;East&quot; &quot;West&quot; ...</code></pre>
<pre class="r"><code>summary(business_data)</code></pre>
<pre><code>##    quarter            channel               year         revenue      
##  Length:48          Length:48          Min.   :2023   Min.   :150231  
##  Class :character   Class :character   1st Qu.:2023   1st Qu.:177597  
##  Mode  :character   Mode  :character   Median :2024   Median :263544  
##                                        Mean   :2024   Mean   :258796  
##                                        3rd Qu.:2024   3rd Qu.:324372  
##                                        Max.   :2024   Max.   :412125  
##                                                                       
##    customers    conversion_rate    region         
##  Min.   : 433   Min.   :2.300   Length:48         
##  1st Qu.: 600   1st Qu.:3.100   Class :character  
##  Median :1223   Median :3.700   Mode  :character  
##  Mean   :1127   Mean   :3.849                     
##  3rd Qu.:1526   3rd Qu.:4.400                     
##  Max.   :1861   Max.   :6.400                     
##                 NA&#39;s   :3</code></pre>
<pre class="r"><code>unique(business_data$channel)</code></pre>
<pre><code>## [1] &quot;Online&quot; &quot;Mobile&quot; &quot;Retail&quot;</code></pre>
<p><u>Quarter</u></p>
<p>The data called <strong>quarter</strong> is either:</p>
<ul>
<li>Q1 January–March</li>
<li>Q2 April–June</li>
<li>Q3 July–September</li>
<li>Q4 October–December</li>
</ul>
<p>This demonstrates that <strong>quarter</strong> is numerical data
referring to a specific quarter of the year.</p>
<p><u>Channel</u></p>
<p>The data called <strong>“channel”</strong> is referring to the source
of different revenue streams, which include the following:</p>
<ul>
<li>Online</li>
<li>Mobile</li>
<li>Retail</li>
</ul>
<p><u>Revenue</u></p>
<p>The range of revenue values goes from a minimum of
<strong>$150,230</strong> to a maximum of <strong>$412,125.</strong></p>
<hr />
</div>
<div id="section-2" class="section level3">
<h3></h3>
<pre class="r"><code>channel_totals &lt;- aggregate(revenue ~ channel, data = business_data, FUN = sum)

channel_totals</code></pre>
<pre><code>##   channel revenue
## 1  Mobile 4158056
## 2  Online 5571130
## 3  Retail 2693023</code></pre>
<pre class="r"><code>aggregate(customers ~ quarter, data = business_data, FUN = mean)</code></pre>
<pre><code>##   quarter customers
## 1      Q1  1069.000
## 2      Q2  1153.583
## 3      Q3  1172.917
## 4      Q4  1110.750</code></pre>
<p><u>Total Revenue</u></p>
<p>The <strong>online</strong> channel generates the most revenue
overall.</p>
<p><u>Customers In Quarters</u></p>
<p><strong>Quarter 3 (Q3)</strong> has the most customers.</p>
<hr />
</div>
<div id="link2" class="section level3">
<h3></h3>
<pre class="r"><code>business_data$revenue_per_customer &lt;- business_data$revenue / business_data$customers

aggregate(revenue_per_customer ~ channel, 
                         data = business_data, 
                         FUN = mean)</code></pre>
<pre><code>##   channel revenue_per_customer
## 1  Mobile             202.8074
## 2  Online             224.3320
## 3  Retail             314.2239</code></pre>
<p><u>Highest Average Revenue Per Customer </u></p>
<p>The <strong>retail</strong> location has the highest average revenue
per customer. This tells us that the retail locations have a sales
advantage that could be due to many different reasons such as better
upselling, better marketing or different consumer behavior psychology of
in-person shopping.</p>
<hr />
</div>
</div>
<div id="section-3" class="section level2">
<h2></h2>
<div id="section-4" class="section level3">
<h3></h3>
<pre class="r"><code># Turned Off Scientific Notation For Ease Of Understanding
options(scipen = 999)


channel_totals &lt;- aggregate(revenue ~ channel, data = business_data, sum)

ggplot(channel_totals, aes(x = channel, y = revenue)) +
  geom_bar(stat = &quot;identity&quot;) +
  labs(title = &quot;Total Revenue by Channel&quot;, 
       x = &quot;Sales Channel&quot;, y = &quot;Revenue ($)&quot;)</code></pre>
<p><img src="project2_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p><u> Investnment Allocation </u></p>
<p>The channel with the highest total revenue is online followed by
mobile than retail. Therefore, based off this data visualization the
online channel should receive more investment because it already
demonstrates the highest profitability.</p>
<hr />
</div>
<div id="link" class="section level3">
<h3></h3>
<pre class="r"><code>ggplot(business_data, aes(x = customers, y = revenue, color = channel)) +
  geom_point(size = 3) +
  labs(title = &quot;Customer Count vs Revenue by Channel&quot;,
       x = &quot;Number of Customers&quot;, y = &quot;Revenue ($)&quot;)</code></pre>
<p><img src="project2_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p><u> Conversion Of Customers to revenue </u></p>
<p>The scatter plot shows that although mobile and online channels make
the most profit they also have significantly more customer reach then
the physical retail channel. This demonstrates that the most efficient
channel to convert customers to revenue is <strong>retail</strong>
because it has a very small reach but still demonstrate <strong>high
relative profits.</strong></p>
<hr />
</div>
</div>
<div id="section-5" class="section level2">
<h2></h2>
<div id="section-6" class="section level3">
<h3></h3>
<pre class="r"><code># I was having issues with CBIND so i used mergers instead.

library(knitr)


avg_customers &lt;- aggregate(customers ~ channel, data = business_data, FUN = mean)


avg_conversion &lt;- aggregate(conversion_rate ~ channel, data = business_data, FUN = mean)

# Merging data.

performance_summary &lt;- merge(channel_totals, avg_customers, by = &quot;channel&quot;)

# Merging avg_conversion into preformance summary beacause merging can only be done two at a time.

performance_summary &lt;- merge(performance_summary, avg_conversion, by = &quot;channel&quot;)

# Digits @ 2 is specfically important for &quot;avg conversion rate&quot;. 

kable(
  performance_summary,
  digits = 2,
  caption = &quot;Channel Performance Summary&quot;,
  col.names = c(&quot;Channel&quot;, &quot;Total Revenue ($)&quot;, &quot;Average Customers&quot;, &quot;Average Conversion Rate (%)&quot;)
)</code></pre>
<table>
<caption>Channel Performance Summary</caption>
<colgroup>
<col width="11%" />
<col width="25%" />
<col width="25%" />
<col width="38%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Channel</th>
<th align="right">Total Revenue ($)</th>
<th align="right">Average Customers</th>
<th align="right">Average Conversion Rate (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Mobile</td>
<td align="right">4158056</td>
<td align="right">1278.06</td>
<td align="right">2.88</td>
</tr>
<tr class="even">
<td align="left">Online</td>
<td align="right">5571130</td>
<td align="right">1559.56</td>
<td align="right">3.64</td>
</tr>
<tr class="odd">
<td align="left">Retail</td>
<td align="right">2693023</td>
<td align="right">542.06</td>
<td align="right">5.03</td>
</tr>
</tbody>
</table>
<hr />
</div>
<div id="section-7" class="section level3">
<h3></h3>
<p><u> Strategic Reconmmendation </u></p>
<p>In <a href="#link">Section 2.2</a> and <a href="#link2">Section
1.3</a> it is demonstrated that the retail channel convertes customers
to revenue most efficiently. The data in <a href="#link2">Section
1.3</a> demonstrates the following:</p>
<p><strong>Revenue Per Customer</strong></p>
<ul>
<li>Mobile 202.8074</li>
<li>Online 224.3320</li>
<li><strong>Retail 314.2239</strong></li>
</ul>
<p>In other words, the retail channel demonstrates the highest profit
per customer. Therefore Increased <strong>in-store promotions</strong>
should be created to help drive more traffic and take advantage of
retail stores high conversion rate of <strong>5.03%.</strong></p>
<hr />
<hr />
<p><a href="projects.html">← Back to Projects</a> | <a
href="index.html">← Back to Home</a></p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
